In [1]:
import numpy as np

-> Write a NumPy program to test whether none of the elements of a given array are zero.

In [ ]:
x = np.array([0, 1, 2, 3])
print(np.all(x))   #Return False cause the array x do have 0 in it.

x = np.array([0, 1, 0, 0])
print(np.any(x))    #Return True becasue the array X do have a non-zero element.

-> Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [ ]:
arr = np.array([1, 0, np.inf, np.nan, -np.inf, 2.5])
print(np.isfinite(arr)) #It returns a boolean array of the same shape, with True indicating a finite number and False indicating a non-finite number.

arr = np.array([1, 0, np.inf, np.nan, -np.inf, 2.5])
print(np.isposinf(arr)) #Return true for that element which is positive infinite.

-> Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.

In [ ]:
array = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
a = 2
print(np.iscomplex(array))   #Return true if the element is a complex.
print(np.isreal(array))   #Return true if the element is a real.
print(np.isscalar(array))   #Return true if the element is a scaler.
#  In NumPy, a scalar element refers to a single value inside a NumPy array — not an array or list itself, but just one numerical value (like an int, float, or even a complex number).
print(np.isscalar(a))

--> Convert a array to list.

In [ ]:
l = [1,2,3,4]
np.array(l)

--> Create a 3 dimensional array.

In [ ]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3.ndim)

3


--> Create a multidimensional array.

In [21]:
var = np.array([1,2,3,4,5],ndmin = 5)
print(var)

[[[[[1 2 3 4 5]]]]]


--> Create a zero array.

In [ ]:
zero_array = np.zeros(4)
zero_array1 = np.zeros((3,4))   #Creates a 2D array of 3 rows and 4 columns.
print(zero_array1,"\n")

one_array = np.ones(6)
print(one_array,"\n")   #Creates an 1D array of 6 columns and 1 row.

new = one_array.reshape(2,3)    #Reshape the 1D array to a 2D array of 2 Rows and 3 Columns.
print(new)

--> Rearanging an existing array.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
new = arr.reshape(3,2)
print(new)

Create an empty array.

In [ ]:
emp_array = np.empty(6)
print(emp_array)

--> Create an array with digonal element as 1.

In [ ]:
ar_dia = np.eye(5,5)
print(ar_dia)   #Creates a square matrix type array with digonal entries 1.

--> Create an array with a perticular gap.

In [3]:
ar_lin = np.linspace(0,10,num = 6)
print(ar_lin)

[ 0.  2.  4.  6.  8. 10.]


--> Creating a random array.

In [ ]:
var = np.random.rand(2)   #Creates a positive number between 0 to 1
print(var,"\n")

var1 = np.random.randn(2)   #Creates both positive and negetive number
print(var1,"\n")

var2 = np.random.ranf(4)    #Creates array with numbers between [0,1)
print(var2,"\n")

var3 = np.random.randint(4,16,6)    #Creates 6 numbers between 4 and 16.
print(var3)

## Datatype in Numpy array

In [ ]:
var = np.array([10, 20, 30, 40, 50, 60],dtype=np.int32)     # Change the datatype to int32
# print(var.dtype)

new = np.float32(var)   #Converts the data type to float.
print(var.dtype)
print(new.dtype)
print(var)
print(new)

In [ ]:
var = np.array([10, 20, 30, 40, 50, 60])
new_var = var.astype(float)     # This will convert the integer datatype to a float data type.
print(new_var)

## Arithmetic Operation in NumPy Arrays.

--> For 1D array.

In [ ]:
var1 = np.array([1,0,3,4,5])
var2 = np.array([7,8,9,6,5])

var_add = var1 + 3   #Add 3 to each element of the array.
print(var_add,"\n")

var_sub = var1 - var2   # Or can also use ar_sub = np.sub(var1 , var2)
print(var_sub,"\n")     # Subtract each element of var2 from the same positioned element of var1.

var_mul = var1 * var2   # np.multiply(var1, var2)
print(var_mul,"\n") 

var_div = var1 / var2   # np.divide(var1, var2)
print(var_div,"\n")

var_mod = var1 % var2   # np.mod(var1, var2)
print(var_mod,"\n")     # Returns the remainder when var1 is divided by var2.

var_pow = var1**var2    # np.power(var1,var2)
print(var_pow,"\n")

var_res = 1 / var1      # np.reciprocal(var1)
print(var_res,"\n")


--> For 2D array

In [ ]:
var1 = np.array([[1,2,3,4,5], [8,5,2,1,6]])
var2 = np.array([[7,8,9,6,5], [9,4,6,3,7]])

var_add = var1 + var2   #Add 3 to each element of the array.
print(var_add,"\n")

var_sub = var1 - var2   # Or can also use ar_sub = np.sub(var1 , var2)
print(var_sub,"\n")     # Subtract each element of var2 from the same positioned element of var1.

var_mul = var1 * var2   # np.multiply(var1, var2)
print(var_mul,"\n") 

var_div = var1 / var2   # np.divide(var1, var2)
print(var_div,"\n")

var_mod = var1 % var2   # np.mod(var1, var2)
print(var_mod,"\n")     # Returns the remainder when var1 is divided by var2.

var_pow = var1**var2    # np.power(var1,var2)
print(var_pow,"\n")

var_res = 1 / var1      # np.reciprocal(var1)
print(var_res,"\n")


## Arithematic Operations in NumPy

--> 1D array

In [ ]:
var = np.array([1,2,3,4,5])
print("Min: ",np.min(var), "Index Number: ", np.argmin(var))    # np.argmin(var) will return the index number of min value in the array.
print("Max: ",np.max(var), "Index Number: ", np.argmax(var))    # np.argmax(var) will return the index number of max value in the array.


--> 2D array

In [ ]:
var = np.array([[1,2,3,4,5] , [8,9,7,4,6]])
print(var,"\n")

print("Minimum along the rows: ",np.min(var, axis=1),"\n")   # axis = 1 suggests the operation to be row wise.
print("Maximum along the columns: ", np.max(var, axis = 0),"\n")     # axis = 0 suggests to perform the operation column wise.

print("Square Root of each element: ", np.sqrt(var),"\n")

print("sin of each element: ", np.sin(var),"\n")
print("cos of each element: ", np.cos(var),"\n")

--> CUMSUM function

In [37]:
#    numpy. cumsum() function is used to compute the cumulative sum of elements in an array. Cumulative sum refers to a sequence where each element is the sum of all previous elements plus itself.
var = np.array([1,2,3,4,5])
print(np.cumsum(var))

[ 1  3  6 10 15]


## Shape and Reshaping in NumPy Arrays.

--> Shape in Numpy

In [ ]:
var = np.array([[1,2,5],[4,6,5]])
var1 = np.array([1,2,3,4,5],ndmin=5)

print(var)
print(var.shape,"\n")       # The output (2,3) means the first dimension have 2 elements and the 2nd dimension have 3 elements init.

print(var1)
print(var1.shape)   #   (1, 1, 1, 1, 5), each dimesion have one element but the last one have 5 elements init.

--> Reshape a NumPy array

In [ ]:
var = np.array([[1,2,5],[4,6,5]])
var_new = var.reshape(6)    # Converts the array to a new array which have six element in the first and only dimesion.
var_new1 = var.reshape(1,2,3)   # Now the array becomes 3 dimesional with first dimension having 1, second having 2 and the third having 3 elements each.

print(var_new, "\n")
print(var_new1, "\n")

# To convert back var_new1 again to 1D array:
new = var_new1.reshape(-1) 
print(new)

## Broadcasting in NumPy arrays

In [ ]:
var = np.array([[1],
                [2]])       # Shape : (2 x 1)
var1 = np.array([[1,2,3],
                 [7,8,9]])  # Shape : (2 x 3)  
#  When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#           (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when:
#           1. they are equal, or
#           2. one of them is 1.

print(var + var1,"\n")
print(var - var1,"\n")
print(var * var1,"\n")
print(var % var1,"\n")



## Indexing & Slicing 

--> 1D array

In [24]:
var = np.array([1,2,3,4])
print(var[2])   # Returns the 2nd index in the array
print(var[-3])
 

3
2


--> 2D array

In [ ]:
var = np.array([[1,2,3,4] , [4,5,6,9]])
print(var[0,3])     # Returns the element from the zeroth index of 1st dimension and 3rd index of second dimension.

--> 3D array

In [ ]:
var = np.array([[[1,2,3],[2,5,8]],[[1,7,9],[5,7,3]]])
print(var[1,1,1])
print(var.shape)


7
(2, 2, 3)


--> Slicing an array

In [ ]:
#   [ start : stop : step ]
var = np.array([1,8,9,5,7,66,1,22,48,955,30])
print(var[2:5])     # Mark that this will retun values upto the 4th index.
print(var[2:])
print(var[:4])
print(var[1:6:2])       # The data will jump by 2 position
print(var[::2])

--> 2D array

In [ ]:
var = np.array([[1,2,3,4] , [4,5,6,9]])
print(var[0,1:])    # Start slicing from the zroth element of first dimesion and 1st element of second dimension.

--> 3D array

In [25]:
var = np.array([[[1,2,3],[2,5,8]],[[1,7,9],[5,7,3]]])
print(var[1,0,1:])

[7 9]


## Iteration in NumPy Array

--> Using for loop 

In [ ]:
var1 = np.array([6,5,8,9,7,6,2])
for i in var1:
    print(i)

print()    

var2 = np.array([[1,2,3,4],[5,4,6,9]])
for i in var2:
    print(i)

print()

var3 = np.array([[[1,2,3],[5,2,4]],[[5,8,7],[7,8,3]]])
for i in var3:
    print(i)

--> Using Numpy fucntion 

In [ ]:
var3 = np.array([[[1,2,3],[5,2,4]],[[5,8,7],[7,8,3]]])
for i in np.nditer(var3):
    print(i)
    
for i,data in np.ndenumerate(var3):
    print(i,data)       # Returns the value with the index number.

## Copy and view function 

copy():
--> Use it when you want a completely independent copy of the array.

--> Changes to the new array won’t affect the original array.

In [ ]:
var1 = np.array([6,5,8,9,7,6,2])
cp = var1.copy()

var1[3] = 10    # It will only change in the var1 array not in cp.

print("var1: ",var1)
print("cp: ",cp)

view():
--> Creates a new array object that shares the same data as the original.

--> Changes to one will affect the other.

In [ ]:
var1 = np.array([6,5,8,9,7,6,2])
vw = var1.view()

var1[3] = 10    # It will change in the var1 array alogn with vw.

print("var1: ",var1)
print("cp: ",vw)

## Join & Split Functions

To join two arrays or more  they must have same number of elements.

-->  1D array 

In [28]:
var1 = np.array([1,2,3,4])
var2 = np.array([8,9,6,5])
merge = np.concatenate((var1, var2))
print(merge)

[1 2 3 4 8 9 6 5]


--> 2D & 3D array

In [29]:
var1 = np.array([[1,5,9,6],[5,4,6,9]])
var2 = np.array([[1,2,3,4],[4,8,7,3]])

merge_arr = np.concatenate((var1,var2),axis=1)  # This will merge the array along the row. Axis = 0 for doing along the column.
print(merge_arr)


[[1 5 9 6 1 2 3 4]
 [5 4 6 9 4 8 7 3]]


> Using stack function

In [30]:
var1 = np.array([[1,5,9,6],[5,4,6,9]])
var2 = np.array([[1,2,3,4],[4,8,7,3]])

merge_arr = np.stack ((var1,var2),axis=1)  # This will merge the array along the row. Axis = 0 for doing along the column.

In [26]:
print(var1)
print(var2)

[[1 5 9 6]
 [5 4 6 9]]
[[1 2 3 4]
 [4 8 7 3]]


--> Merge along vertically.

In [27]:
merge_arr = np.hstack ((var1,var2))
print(merge_arr)        #Along horizontal.

[[1 5 9 6 1 2 3 4]
 [5 4 6 9 4 8 7 3]]


--> Merge along the column.

In [28]:
merge_arr = np.vstack ((var1,var2))
print(merge_arr)        # Along vertical.

[[1 5 9 6]
 [5 4 6 9]
 [1 2 3 4]
 [4 8 7 3]]


--> Merge along dimesion.

In [31]:
merge_arr = np.dstack ((var1,var2))
print(merge_arr)    # Merge alogn the dimension.

[[[1 1]
  [5 2]
  [9 3]
  [6 4]]

 [[5 4]
  [4 8]
  [6 7]
  [9 3]]]


> Split array

In [36]:
## 1D array
var1 = np.array([1,2,3,4])
new_var1 = np.array_split(var1,3)
print(new_var1,"\n")

## 2D array
var2 = np.array([[1,2,3,4],[4,8,7,3]])
new_var2 = np.array_split(var2,2)
print(new_var2,"\n")

[array([1, 2]), array([3]), array([4])] 

[array([[1, 2, 3, 4]]), array([[4, 8, 7, 3]])] 



## Search Function 

> Using Where function

In [ ]:
arr = np.array([1,2,3,4,5,2,6,5,7])
var = np.where( arr == 4)   # index number of 4 will be stored inside the var array.
print(var)

(array([3]),)


> Searchsorted function

In [13]:
in_arr = [2, 3, 4, 5, 6]
num = [4, 8, 0]
print("The number which we want to insert : ", num)  

out_ind = np.searchsorted(in_arr, num) 
print ("Output indices to maintain sorted array : ", out_ind) 

result = np.insert(in_arr, out_ind, num)
print("Final array after insertion: ", result)

The number which we want to insert :  [4, 8, 0]
Output indices to maintain sorted array :  [2 5 0]
Final array after insertion:  [0 2 3 4 4 5 6 8]


> You're inserting multiple values into one array.

> Each insertion shifts the array:

  1. When you insert at index 0, all the following indices move right

  2. So the original out_ind becomes outdated after the first insertion!

> 0 inserted at 0 then the other elements shifts right by 1 index, so the the next insertion which is 4 will be inserted at 2+1 = 3rd index, similarly 8 will be inserted at 5+2 = 7th index. 

#  Understanding Tolerance In Numpy.

In [32]:
a = 0.1
b = 0.2
c = 0.3

# Direct comparison
print("a + b == c:", a + b == c)  # Expected: True, Actual: False

# Show the actual result
print("a + b =", a + b)
print("c     =", c)


a + b == c: False
a + b = 0.30000000000000004
c     = 0.3


In [ ]:
# 💡 Why This Happens:
# 0.1 and 0.2 can't be perfectly represented in binary (just like 1/3 can't be in decimal).
# So when Python adds 0.1 + 0.2, the result is slightly more than 0.3 (like 0.30000000000000004).

print("Using np.isclose:", np.isclose(a + b, c))  # Correct way ✅


-> Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [6]:
np.isclose([1,1.000001,1.00002] , [1.00001, 1.001, 1.2], rtol=1e-1, atol=1e-5)
# abs(a-b) <= ( atol + rtol * abs(b))
# atol is that tolerance which shows how much the data 'a' can varies by it's own.

array([ True,  True, False])

# 🧠 NumPy Practice Set (25 Questions)

In [2]:
import numpy as np

> 🔹 Array Creation & Basics

1. Create a 1D array of numbers from 0 to 20 with step 2.

In [5]:
arr = np.arange(0,22,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

2. Create a 3x3 identity matrix.

In [6]:
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3. Create an array of shape (4, 4) filled with random floats between 0 and 1.

In [15]:
arr = np.random.ranf((4,4))
arr

array([[0.76949478, 0.85629508, 0.40686466, 0.62931444],
       [0.27755992, 0.07468858, 0.91416398, 0.46690123],
       [0.68449154, 0.67880611, 0.36870563, 0.36089201],
       [0.22311643, 0.95105382, 0.63133584, 0.70601717]])

4. Create a 5x5 matrix with values from 1 to 25.

In [19]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

5. Create a 2D array where the border is 1 and inside is 0 (5x5).

In [ ]:
arr = np.ones((5,5),dtype=int)
arr[1:-1,1:-1] = 0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

> Indexing & Slicing

6. Extract the middle 3x3 matrix from a 5x5 matrix filled with values from 1 to 25.

In [45]:
arr = np.arange(1,26).reshape((5,5))
arr1 = arr[1:-1,1:-1]
arr1

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

7. Replace all odd numbers in an array with -1.

In [57]:
np.random.seed(5)
arr = np.random.randint(1,100,size=((5,5)))
print(arr)
print()
arr[ arr % 2 != 0] = -1
print(arr)

[[79 62 17 74  9]
 [63 28 31 81  8]
 [77 16 54 81 28]
 [45 78 76 66 48]
 [31 85 87 19 10]]

[[-1 62 -1 74 -1]
 [-1 28 -1 -1  8]
 [-1 16 54 -1 28]
 [-1 78 76 66 48]
 [-1 -1 -1 -1 10]]


8. Extract all elements in a 1D array that are divisible by both 3 and 5.

In [5]:
arr = np.random.randint(0,100,10)
var = arr[arr % 15 == 0 ]
print(arr,"\n",var)

[62 29 30 43 69 53 78 15 57 79] 
 [30 15]


9. Get all rows from a 2D array where the sum is greater than 20.

In [13]:
arr = np.random.randint(0,20,10).reshape(5,2)
print(f"The array is: {arr} \n")
print("Rows in array whose sum is greater than 20: ")
for row in arr:
    if row.sum() > 20:
        print(row)

The array is: [[ 9  4]
 [17  0]
 [ 6  3]
 [ 4  8]
 [ 8 18]] 

Rows in array whose sum is greater than 20: 
[ 8 18]


10. Reverse a 1D array without using loops.

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
rev_arr = arr[::-1]
rev_arr

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

> Mathematical Operations

11. Multiply two matrices using both * and np.dot() and explain the difference.

In [ ]:
arr1 = np.random.ranf((3,3))
print("Array 1 :\n",arr1,"\n")
arr2 = np.random.ranf((3,3))
print("Array 2 :\n",arr2,"\n")

#multiplication = arr1 * arr2
multiplication = np.dot(arr1,arr2)      # only works for square matrix.
print("Multiplication:\n",multiplication)


Array 1 :
 [[0.47130306 0.1596776  0.88100452]
 [0.10189489 0.95278007 0.13664484]
 [0.75301865 0.05330339 0.15283312]] 

Array 2 :
 [[0.75936643 0.99390282 0.40882899]
 [0.53039276 0.22936901 0.54846359]
 [0.54829316 0.61048943 0.5929193 ]] 

Multiplication:
 [[0.92563231 1.04289847 0.80262428]
 [0.65764464 0.40323207 0.64524213]
 [0.68388617 0.85395651 0.42770853]]


12. Normalize an array to bring all values between 0 and 1.

In [ ]:
arr1 = np.random.randint(1,50,27).reshape(3,3,3)
normalized_arr1 = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
#print(arr1)
normalized_arr1

[[[26 35 49]
  [33 35 17]
  [10 28  7]]

 [[48 43 32]
  [29 17 25]
  [18 45 35]]

 [[47 49  8]
  [13 19 34]
  [19 33 42]]]


array([[[0.45238095, 0.66666667, 1.        ],
        [0.61904762, 0.66666667, 0.23809524],
        [0.07142857, 0.5       , 0.        ]],

       [[0.97619048, 0.85714286, 0.5952381 ],
        [0.52380952, 0.23809524, 0.42857143],
        [0.26190476, 0.9047619 , 0.66666667]],

       [[0.95238095, 1.        , 0.02380952],
        [0.14285714, 0.28571429, 0.64285714],
        [0.28571429, 0.61904762, 0.83333333]]])

13. Compute the Euclidean distance between two 1D arrays.

In [ ]:
p1 = np.array([1,2,3])
p2 = np.array([2,8,8])
dist = np.sqrt(sum((p1-p2)**2))
print(dist.round(2))

7.87
[-1 -6 -5]


14. Count the number of values greater than the mean in a random array of size 100.

In [47]:
arr = np.random.randint(100,1000,100)
average = arr.mean()
print(f"Average of the Array is: {average}\n")
num = []
for ele in arr:
    if ele > average:
        num.append(ele)
num_arr = np.array(num)
print(num_arr)

Average of the Array is: 573.01

[711 880 821 765 860 577 698 670 928 951 904 870 897 886 678 738 970 893
 582 798 944 905 839 736 991 593 666 928 997 763 580 935 831 580 595 831
 576 590 732 730 972 885 983 762 994 821 692 689 902 955 679 669 726 987
 790]


15. Find the standard deviation and variance of a 2D array.

In [55]:
arr = np.random.randint(0,100,15).reshape(5,3)
print(arr,"\n")
average = arr.mean()
variance = ((arr - average)**2).sum() / len(arr)
print(f"The variance of the array is : {variance:.2f}\n")
sd = np.sqrt(variance)
print(f"The standard deviation of the data is: {sd:.2f}")

[[51  2 97]
 [52 96 33]
 [14 98 61]
 [73 97 58]
 [48 66 68]] 

The variance of the array is : 2447.39

The standard deviation of the data is: 49.47


> Boolean Logic & Filtering

16. Replace all NaN values in an array with the mean of the non-NaN values.

In [65]:
arr = np.array([1,2,np.nan,5,8,np.nan,13])
avg = np.nanmean(arr)
arr[np.isnan(arr)] = avg
print(arr)

[ 1.   2.   5.8  5.   8.   5.8 13. ]


17. Find the index of the maximum element in a 2D array.

In [66]:
arr = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
max_ele = np.argmax(arr)
max_ele

np.int64(8)

18. Create a mask for values in an array that are negative, and make them 0.

In [ ]:
arr = np.arange(-5,5).reshape(5,2)
print(arr,"\n")
arr[ arr < 0] = 0
print(arr)

19. Check if any row in a matrix has all elements > 10.

In [19]:
arr = np.array([[11, 12, 13],
                [5, 15, 11],
                [14, 16, 17]])

# 1. Perform element-wise comparison
greater_than_10 = arr > 10

# 2. Check if all elements in each row are greater than 10
# (results in a boolean array for each row)
all_in_row_greater_than_10 = np.all(greater_than_10, axis=1)

# 3. Check if any row has all elements greater than 10
any_row_meets_condition = np.any(all_in_row_greater_than_10)
any_row_meets_condition


np.True_

20. How many unique values exist in an array?

In [25]:
arr = np.array([[11, 12, 13],
                [5, 15, 11],
                [14, 16, 17]])
arr_unique = np.unique(arr)
print(arr_unique)

[ 5 11 12 13 14 15 16 17]


> Broadcasting & Advanced Tasks

21. Subtract the row mean from each row in a 2D array.

In [34]:
arr = np.array([[11, 12, 13],
                [5, 15, 11],
                [14, 16, 17]])
arr_mean = np.mean(arr,axis=1).round(2).reshape(3,1)
sub = arr -arr_mean
print(f"For the array:\n{arr}\n")
print(f"The average value array of each column is:\n{arr_mean}\n")
print(f"Array after subtracting the mean array from array :\n{sub}")

For the array:
[[11 12 13]
 [ 5 15 11]
 [14 16 17]]

The average value array of each column is:
[[12.  ]
 [10.33]
 [15.67]]

Array after subtracting the mean array from array :
[[-1.    0.    1.  ]
 [-5.33  4.67  0.67]
 [-1.67  0.33  1.33]]


22. Generate a checkerboard pattern (8x8) using only 0s and 1s.

In [9]:
arr = np.zeros((8,8),dtype=int)
arr[::2,::2] = 1
arr[1::2,1::2] = 1
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


23. Create a 1D array of 1000 numbers and count how many fall between 250 and 750.

In [22]:
arr = np.arange(1,1001)
new = arr[(arr > 250) & ( arr < 750) ] 
count = np.size(new)
count

499

24. Replace the max value in an array with 0, without using np.where.

In [39]:
arr = np.array([5, 2, 99, 7, 30, 99])  # test with repeated max value
max_val = arr.max()
arr[arr == max_val] = 0
print(arr)

[ 5  2  0  7 30  0]
